# Introduction

These pages accompany the book "Geographic Information Analysis" by David O'Sullivan and David J. Unwin [(2nd Edition, 2010)](http://www.wiley.com/WileyCDA/WileyTitle/productCd-0470288574.html) -- hereinafter referred to as "OSU". 

OSU is an excellent and very accessible introduction to spatial data analysis; but it does not show how to practically implement the methods that are discussed. 

Many of the numerical examples in the text are implemented here, and some of the other techniques discussed are illustrated as well. We hope that this allows readers of OSU to get a more hands-on way to understand the material covered; and to apply such approaches in their own work. Throughout these pages reference is made to OSU, and no attempt is made to explain the material to those who have no access to OSU. 

The examples are all implemented with *R*. If you are new to *R*, first go through this [introduction](http://rspatial.org/intr/), and make sure to read a bit about [spatial data handling in R](https://rspatial.org/spatial/) as well. 

