
# Getting and setting Raster* dimensions

Basic parameters of existing Raster* objects can be obtained, and in most cases changed. If there are values associated with a RasterLayer object (either in memory or via a link to a file) these are lost when you change the number of columns or rows or the resolution. This is not the case when the extent is changed (as the number of columns and rows will not be affected). Similarly, with `crs` you can set the projection, but this does not transform the data (see `projectRaster` for that).   


## ncol
The number of columns

## nrow
 The number of rows

## ncell
 The number of cells (can not be set directly, only via ncol or nrow)

## res
 The resolution (x and y)

## nlayers
 How many layers does the object have?	

## names
 Get or set the layer names	

## xres
 The x resolution (can be set with res)

## yres
 The y resolution (can be set with res)

## xmin
 The minimum x coordinate (or longitude)

## xmax
 The maximum x coordinate (or longitude)

## ymin
 The minimum y coordinate (or latitude)

## ymax
 The maximum y coordinate (or latitude)

## extent
 The extent (minimum and maximum x and y coordinates)

## origin
 The origin of a Raster* object

## projection
 The coordinate reference system (map projection)	

## isLonLat
 Test if an object has a longitude/latitude coordinate reference system

## filename
 Filename to which a RasterLayer or RasterBrick is linked	

## band
 layer (=band) of a multi-band file that this RasterLayer is linked to	

## nbands
 How many bands (layers) does the file have?	

## compareRaster
 Compare the geometry of Raster* objects		

## NAvalue
 Get or set the `NA` value (for reading from a file)

