# 1. Introduction

*R* is perhaps the most powerful computer environment for data analysis that is currently available. *R* is both a computer *language*, that allows you to write instructions, and a *program* that responds to these instructions. *R* has core functionality to read and write files, manipulate and summarize data, run statistical tests and models, make fancy plots, and many more things like that. This core functionality is extended by hundreds of packages (plug-ins). Some of these packages provide more advanced generic functionality, others provide highly specialized and cutting-edge methods that are only used in highly specialized analysis. 

Because of its versatility, *R* has become very popular across data analysts in many fields, from agronomy to bioinformatics, ecology, finance, geography, pharmacology and psychology. You can read about it in this article in [Nature](http://www.nature.com/news/programming-tools-adventures-with-r-1.16609) or in the [New York Times](http://www.nytimes.com/2009/01/07/technology/business-computing/07program.html?pagewanted=all&_r=0). So you probably should learn *R* if you want to do modern data analysis, be a successful researcher, collaborate, get a [high paying job](http://www.sfgate.com/technology/businessinsider/article/10-Tech-Skills-That-Will-Earn-You-Over-100-000-5193599.php), ... If you are not that much into *data analysis* but want to learn programming, I would suggest that you learn [python](https://docs.python.org/2/tutorial/) instead. 

This document provides a concise introduction to *R*. It emphasizes what you need to know to be able to use the language in any context. There is no fancy statistical analysis here. We just present the basics of the *R* language itself. We do not assume that you have done any computer programming before (but we do assume that you think it is about time you did). Experienced *R* users obviously need not read this. But the material may be useful if you want to refresh your memory, if you have not used *R* much, or if you feel confused. 

When going through the material, it is very important to follow [Norman Matloff](https://www.nostarch.com/artofr.htm)'s advice: *"When in doubt, try it out!"*. That is, copy the examples shown, and then make modifications to test if you can predict what will happen. Only then will you really understand what is going on. You are learning a language, and you will have to practice a lot to become good at it. And you just have to accept that for a while you will be stumbling.

To work with *R* on your own computer, you need to [download](https://cran.r-project.org/) the program and install it. I recommend that you also install [R-Studio](https://www.rstudio.com/). R-Studio is a separate program that makes *R* easier to use. Here is a [video](https://www.youtube.com/watch?v=jwBgGS_4RQA) that shows how to work in R-Studio.

If you have trouble with the material presented here, you could consult additional resources to learn *R*. There are many free resources on the web, including [R for Beginners](http://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf) by Emmanuel Paradis and this [tutorial](http://www.cyclismo.org/tutorial/R/). Or consult this [brief overview](https://www.stat.auckland.ac.nz/~ihaka/120/Notes/ch02.pdf) by Ross Ihaka (one of the originators of R) from his [Information Visualization](https://www.stat.auckland.ac.nz/~ihaka/120/notes.html) course. You can also pick up an introductory *R* book such as [A Beginner's Guide to R](http://www.springer.com/us/book/9780387938363) by Zuur, Leno and Meesters, [R in a nutshell](http://shop.oreilly.com/product/0636920022008.do) by Joseph Adler, and Norman Matloff's [The Art of R Programming](http://www.nostarch.com/artofr.htm). There are also other on-line resources such as  you might also try Datacamp’s [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r).

There is also a lot of very good material on [rstatistics.net](http://rstatistics.net/)

If you want to take it easy, or perhaps learn about R while you commute on a packed train, you could watch some [Google Developers videos](http://www.youtube.com/playlist?list=PLOU2XLYxmsIK9qQfztXeybpHvru-TrqAP).

If none of this appeals to you, and you already are experienced with *R*, or you have done a lot of programming with other languages, skip all of this and have a look at Hadley Wickham's [Advanced R](http://adv-r.had.co.nz/).

You can [download this manual as a pdf](../../_sources/intr/rst/IntroductiontoR.pdf).


## Installing the R and R Studio software

### Windows
####Install R
[Download](https://cran.r-project.org/bin/windows/base/) the latest R installer (.exe) for Windows 
Install the downloaded file as any other windows app. 

If you encounter problems, read [this](https://cran.r-project.org/bin/windows/base/README.R-3.5.1), 

####Install RStudio
Now that R is installed, you need to download and install RStudio. 
First [download](https://www.rstudio.com/products/rstudio/download/#download) the installer for Windows.
Run the installer (.exe file) and follow the instructions.


### Mac
#### Install R
First [download](https://cran.r-project.org/bin/macosx/) the latest release ("R-version.pkg") of R
Save the .pkg file, double-click it to open, and follow the installation instructions.
Now that R is installed, you need to download and install RStudio.

####Install RStudio
First [Download] the the version for Mac. After downloading, double-click the file to open it, and then drag and drop it to your applications folder.


###Linux
####Install R
Go to [this web page](https://cran.r-project.org/bin/linux/) and open the folder based on your linux distribution and follow the instricutions in the 'readme'. 

####Install RStudio
It is difficult to provide a single guideline for different linux distributions. Please follow the general steps below:
Go to https://www.rstudio.com/products/rstudio/download/#download and download the installer for the linux distribution you are using 
Install the downloaded file as any linux installer  

Ubuntu users are advised to follow the instructions in this [discussion on stackoverflow](https://stackoverflow.com/questions/44382368/rgdal-installation-difficulty-on-ubuntu-16-04-lts) to avoid complexity in installing some of the ‘spatial` packages, particularly ‘rgdal`.



